<?php
echo "<pre>";
print_r($this->request->getPost());
$htm = "";
if (isset($data)) {

    foreach ($data as $key => $value) {
        // echo "<br>";
        // print_r($value->name);
        $htm .= "
            <tr>
                <th scope='row'>$value->name</th>
                <td>$value->password</td>
                <td>
                <input type='hidden' name='id' value='$value->_id'>
                <button class='btn btn-warning' name='edit' value='$value->_id'>Edit</button>
                <button class='btn btn-danger'  name='delete' value='$value->_id'>Delete</button>
                </td>

            </tr>
        ";
    }
}

$name = "";
$email = "";
$id = "";
if (isset($editData)) {

    $name = $editData['name'];
    $email = $editData['password'];
    $id = $editData["_id"];

    // die;
}

echo "</pre>";
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>

    <div class="h1 text-center">Crud Operations</div>
    <form method="post">
        <input type="text" class="form-control text-center text-danger" name="name" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder=Name" value="<?php echo $name ?>">

        <input type="text" class="form-control text-center text-danger mt-2" name="password" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email" value="<?php echo $email ?>">

        <input type="hidden" name="id" value="<?php echo $id ?>">

        <div class="d-flex justify-content-center mt-2">
            <input type="submit" class="btn btn-primary" name="action" value="Save">
            <input type="submit" class="btn outline btn-success ml-3" name="action" value="Update">

        </div>
    </form>

    <div class="h3 text-warning text-center mt-5">User Data</div>
    <form action="" method="post">
        <table class="table table-bordered text-center">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Email Address</th>
                    <th scope="col">Actions</th>

                </tr>
            </thead>
            <tbody>
                <?php
                if (isset($data)) {
                    echo $htm;
                } else {
                    echo "<tr><td>Not Found</td><td>Not Found</td><td>Not Found</td></tr>";
                }
                ?>

            </tbody>
        </table>
    </form>
</body>

</html>